### ISSUE TITLE
DefineEvent when compiling wZeeGrid

### ISSUE THREAD

**Issue by leeooox** [bunkford/wZeeGrid#1]
Hi,

When I am compile the example, a error showed "Error: undeclared identifier: 'DefineEvent'".
I am using nim 1.2.6 on Win10 64bit OS.

Full compile logs:

nim c -r "c:\work\prog\nim\wZeeGrid\examples\grid.nim"
Hint: used config file 'C:\work\software\nim-1.2.6_x64\nim-1.2.6\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]      
Hint: grid [Processing]
Hint: wApp [Processing]
Hint: wApp [Processing]
Hint: tables [Processing]
Hint: hashes [Processing]
Hint: math [Processing]
Hint: bitops [Processing]
Hint: macros [Processing]
Hint: algorithm [Processing]
Hint: utils [Processing]
Hint: windef [Processing]
Hint: winimbase [Processing]
Hint: winstr [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: unicode [Processing]
Hint: winimx [Processing]
Hint: wTypes [Processing]
Hint: times [Processing]
Hint: options [Processing]
Hint: typetraits [Processing]
Hint: winlean [Processing]
Hint: dynlib [Processing]
Hint: time_t [Processing]
Hint: sets [Processing]
Hint: lists [Processing]
Hint: sequtils [Processing]
Hint: kiwi [Processing]
Hint: variable [Processing]
Hint: constraint [Processing]
Hint: expression [Processing]
Hint: term [Processing]
Hint: strength [Processing]
Hint: util [Processing]
Hint: symbolics [Processing]
Hint: symbolicints [Processing]
Hint: solver [Processing]
Hint: symbol [Processing]
Hint: row [Processing]
Hint: wMacros [Processing]
Hint: strformat [Processing]
Hint: wHelper [Processing]
Hint: wColors [Processing]
Hint: wKeyCodes [Processing]
Hint: wFrame [Processing]
Hint: wFrame [Processing]
Hint: wBase [Processing]
Hint: wWindow [Processing]
Hint: wUtils [Processing]
Hint: wDataObject [Processing]
Hint: wBitmap [Processing]
Hint: wImage [Processing]
Hint: wIconImage [Processing]
Hint: wGdiObject [Processing]
Hint: wFont [Processing]
Hint: wBrush [Processing]
Hint: wCursor [Processing]
Hint: wEvent [Processing]
Hint: wMouseEvent [Processing]
Hint: wKeyEvent [Processing]
Hint: wSizeEvent [Processing]
Hint: wMoveEvent [Processing]
Hint: wContextMenuEvent [Processing]
Hint: wScrollWinEvent [Processing]
Hint: wTrayEvent [Processing]
Hint: wDragDropEvent [Processing]
Hint: wDialogEvent [Processing]
Hint: wNavigationEvent [Processing]
Hint: wSetCursorEvent [Processing]
Hint: wCommandEvent [Processing]
Hint: wStatusBarEvent [Processing]
Hint: wScrollEvent [Processing]
Hint: wListEvent [Processing]
Hint: wTreeEvent [Processing]
Hint: wSpinEvent [Processing]
Hint: wHyperlinkEvent [Processing]
Hint: wIpEvent [Processing]
Hint: wWebViewEvent [Processing]
Hint: wResizable [Processing]
Hint: autolayout [Processing]
Hint: wResizer [Processing]
Hint: wAcceleratorTable [Processing]
Hint: wPanel [Processing]
Hint: wPanel [Processing]
Hint: wZeeGrid [Processing]
Hint: wControl [Processing]
c:\work\prog\nim\wZeeGrid\wZeeGrid.nim(452, 1) Error: undeclared identifier: 'DefineEvent'

**Comment by bunkford** [comment]
do a `nimble install wZeeGrid` to upgrade to version 1.0.1. I just pushed a fix for this problem.

**Comment by leeooox** [comment]
@bunkford thanks, and it works
