### ISSUE TITLE
Cannot apply proc  interpretNumeric to false

### ISSUE THREAD

**Issue by leeooox** [bunkford/wZeeGrid#2]
Hi,
 
I want to use text and disable it convert to number automatically.

eg. I want to input cell value to be 123. and I don't want it become 123.00

I simply apply this function, but it seems not work.
grid.interpretNumeric(false) 

![image](https://user-images.githubusercontent.com/5811433/103403494-44b23880-4b8b-11eb-9d97-7c51270a9321.png)

**Comment by bunkford** [comment]
I'm not sure why that isn't working. You can set the number precision of the column using the code below. It will still be right justified though.  Even setting the justification of the column doesn't seem to effect that. 
 
```nim
 grid.setColNumPrecision(5, 0)
```

**Comment by bunkford** [comment]
I emailed the author of ZeeGird and asked for clarification if this works, or how it is to be used. I'll update with response.

**Comment by bunkford** [comment]
so apparently the documentation was wrong..

> The documentation is incorrect for INTERPRETNUMERIC.  It is column based.  WPARAM is the column.  LPARAM is the boolean TRUE or FALSE.  WPARAM = -1 for entire grid.

I've update wZeeGrid and the documentation. The -1 for entire grid still doesn't seem to work.

**Comment by bunkford** [comment]
Update: Apparently there is no mechanism to apply these to the entire grid at once using -1.. so you would have to loop through all the columns in your grid if that is what you want to do.

I hope this solves your problem.

**Comment by leeooox** [comment]
I found grid.setDefaultRestriction(0) is work for entire cells.
BTW: grid.setColNumPrecision(col_index, 0) is also work for the column col_index. Thanks.

But my problem is I want all the cells to be treated as "text" and align to left, but the ZeeGrid always "smartly" treat numbers to align right.
As the picture below. the "12" is left align , and "1F" is right align. The intention is both "12" and "1F" align left.

![image](https://user-images.githubusercontent.com/5811433/103438231-08a2d480-4c6c-11eb-91ce-b88dd70b9d5c.png)

**Comment by bunkford** [comment]
I'm assuming Data is your 5th column, so if you update to latest wZeeGrid and use the code below, it should interpret your number as text and align it to the left. 

```nim
  grid.interpretNumeric(5, false)
```

**Comment by leeooox** [comment]
@bunkford,
I upgraded wZeeGrid to 1.0.2 and confirmed it solved the problem with updated function. 
```nim
proc interpretNumeric*(self: wZeeGrid, iCol:int, fEnable:bool = true)
```
Thank you very much, I guess this Grid control could be used in my project.


![image](https://user-images.githubusercontent.com/5811433/103438969-b9f93880-4c73-11eb-8324-a272d008b3a1.png)
