### ISSUE TITLE
Auto extend last column to fill grid space

### ISSUE THREAD

**Issue by super-tomcat** [bunkford/wZeeGrid#5]
In a lot of grid controls there is an option to automatically extend the last column to fill the space upto the edge of the grid control.

This is useful as it can automatically fill in an ugly gap that always appears to the right of the grid and the panel or window it is in.

However i cannot see that option available in wZeeGrid?

At the moment i am having to use a workaround involving adding all the column sizes and subtracting this from the grid size and then using a percentage of what is left to resize the columns to fit.

**Comment by bunkford** [comment]
I think you have to use a work around for this. The original author has retired his code and this wasn't an included feature.
